### ISSUE TITLE
Exception from set_detector_window() for windows outside original calibration

### ISSUE THREAD

**Issue by ssilburn** [euratom-software/calcam#133]
There is an exception being raised by Calibration.set_detector_window() for windows which stray outside the detector area of the original calibrated image:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\calcam\calcam\calibration.py", line 615, in set_detector_window
    padded_im = np.zeros((max(self.geometry.offset[1] + orig_shape[1],window[1]+window[3]),max(self.geometry.offset[0] + orig_shape[0],window[0]+window[2]),self.native_image.shape[2]),self.native_image.dtype)
TypeError: 'float' object cannot be interpreted as an integer

It appears this is not to do with the input dtypes as it's definitely happening when all elements of the input sequence are integers.

**Comment by ssilburn** [comment]
Fixed in release 2.14.1 (I think)
