### ISSUE TITLE
Exception from Calibration.project_points()

### ISSUE THREAD

**Issue by ssilburn** [euratom-software/calcam#134]
Following exception rasied from project_points() - looks like it could be due to a change in int type handling somewhere?

DIAGNOSTIC INFORMATION
----------------------

Platform:       win32
Python version: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
Calcam version: 2.14.0
VTK version:    9.3.1
OpenCV version: 4.10.0
PyQt version:   5.15.2

Traceback (most recent call last):
  File "C:\Users\Thomas\venv\calcam\Lib\site-packages\calcam\gui\fitting_calib.py", line 976, in toggle_reprojected
    projected = self.calibration.project_points(points)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas\venv\calcam\Lib\site-packages\calcam\calibration.py", line 1503, in project_points
    wrong_subview_mask = self.subview_lookup(p2d[:,0],p2d[:,1]) != nview
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas\venv\calcam\Lib\site-packages\calcam\calibration.py", line 1136, in subview_lookup
    out[good_mask == 0] = -1
    ~~~^^^^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint8

**Comment by ssilburn** [comment]
Fixed in release 2.14.1
