### ISSUE TITLE
Bug in view tree with multi-FOV cameras

### ISSUE THREAD

**Issue by ssilburn** [euratom-software/calcam#7]
When trying to click a sub-field of a split FOV calibration in the viewport tab, the code seems to try to load a calibration filename based on the sub-FOV name rather than the main save name. For example:

Traceback (most recent call last):
File "/home/pc/calcam/bin/calcam/gui.py", line 944, in change_cad_view
view = fitting.VirtualCalib(str(view_item.text(0)))
File "/home/pc/calcam/bin/calcam/fitting.py", line 1088, in __init__
self.load(SaveName)
File "/home/pc/calcam/bin/calcam/fitting.py", line 1174, in load
SaveFile = open(os.path.join(paths.virtualcameras,SaveName + '.pickle'),'rb')
IOError: [Errno 2] No such file or directory: '/home/pc/calcam/VirtualCameras/Sub FOV # 1.pickle'

**Comment by ssilburn** [comment]
Fixed - for some reason the if...elif choosing what type of root the selected view came from had stopped working properly, re-ordering it fixed the problem.
